/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifiestoRouteImport } from './routes/manifiesto'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CausaRouteImport } from './routes/causa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriasSlugRouteImport } from './routes/historias.$slug'

const ManifiestoRoute = ManifiestoRouteImport.update({
  id: '/manifiesto',
  path: '/manifiesto',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CausaRoute = CausaRouteImport.update({
  id: '/causa',
  path: '/causa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasSlugRoute = HistoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HistoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/causa': typeof CausaRoute
  '/contacto': typeof ContactoRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/manifiesto': typeof ManifiestoRoute
  '/historias/$slug': typeof HistoriasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/causa': typeof CausaRoute
  '/contacto': typeof ContactoRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/manifiesto': typeof ManifiestoRoute
  '/historias/$slug': typeof HistoriasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/causa': typeof CausaRoute
  '/contacto': typeof ContactoRoute
  '/historias': typeof HistoriasRouteWithChildren
  '/manifiesto': typeof ManifiestoRoute
  '/historias/$slug': typeof HistoriasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/causa'
    | '/contacto'
    | '/historias'
    | '/manifiesto'
    | '/historias/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/causa'
    | '/contacto'
    | '/historias'
    | '/manifiesto'
    | '/historias/$slug'
  id:
    | '__root__'
    | '/'
    | '/causa'
    | '/contacto'
    | '/historias'
    | '/manifiesto'
    | '/historias/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CausaRoute: typeof CausaRoute
  ContactoRoute: typeof ContactoRoute
  HistoriasRoute: typeof HistoriasRouteWithChildren
  ManifiestoRoute: typeof ManifiestoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifiesto': {
      id: '/manifiesto'
      path: '/manifiesto'
      fullPath: '/manifiesto'
      preLoaderRoute: typeof ManifiestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causa': {
      id: '/causa'
      path: '/causa'
      fullPath: '/causa'
      preLoaderRoute: typeof CausaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias/$slug': {
      id: '/historias/$slug'
      path: '/$slug'
      fullPath: '/historias/$slug'
      preLoaderRoute: typeof HistoriasSlugRouteImport
      parentRoute: typeof HistoriasRoute
    }
  }
}

interface HistoriasRouteChildren {
  HistoriasSlugRoute: typeof HistoriasSlugRoute
}

const HistoriasRouteChildren: HistoriasRouteChildren = {
  HistoriasSlugRoute: HistoriasSlugRoute,
}

const HistoriasRouteWithChildren = HistoriasRoute._addFileChildren(
  HistoriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CausaRoute: CausaRoute,
  ContactoRoute: ContactoRoute,
  HistoriasRoute: HistoriasRouteWithChildren,
  ManifiestoRoute: ManifiestoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
